/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "iostream"
#include "sstream"
#include "fstream"
#include "string"
#include "stdio.h"
#include "stdlib.h"
#include "json.hpp"

/* Header for class headers_jni_test_file */

#ifndef _Included_headers_jni_test_file
#define _Included_headers_jni_test_file
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     headers_jni_test_file
   * Method:    TESTSEQ
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_headers_1jni_1test_1file_TESTSEQ(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
